### ISSUE TITLE
after deployed on own dyno only freeze on pending !

### ISSUE THREAD

**Issue by kakamband** [AsaadMe/Director#5]
Hi Mehran,
after deployed on own dyno only freeze on pending after put youtube link & pressed Submit button,
if any env value/s must be set or any buildpack/s needed , tell me to resolve it.
waiting for your response
finest regards
my own dyno url for test is : https://directtube.herokuapp.com/

**Comment by AsaadMe** [comment]
Hi, you should set a "secret" key with any value. but the main problem solved in last commit. please update your fork.
there is still a problem in the latest commit which would cause it to crash when getting large files. you can use [Previous Version](https://github.com/AsaadMe/Director/tree/v0.1) of this project which didn't have this problem but there was another one with its scalability. in case of using version 0.1 there is no need to set a value in heroku.
i think its easier to change the branch you want to deploy on heroku so you can use [this branch](https://github.com/AsaadMe/Director/tree/without_socketio) which refers to v0.1.
thanks.
